// Location data for vote form
// Mexico: organized by metropolitan area (CONAPO 2018, 74 metro areas)
// USA: organized by state with major MSA cities
// Spain: organized by autonomous community
const LOCATION_DATA = {
  "México": {
    "Ciudad de México": ["Ciudad de México","Ecatepec","Nezahualcóyotl","Naucalpan","Tlalnepantla","Chimalhuacán","Iztapalapa","Tultitlán","Cuautitlán Izcalli","Atizapán de Zaragoza","Texcoco","Chalco","Ixtapaluca"],
    "Monterrey": ["Monterrey","Guadalupe","Apodaca","San Nicolás de los Garza","San Pedro Garza García","Santa Catarina","General Escobedo","Juárez","García"],
    "Guadalajara": ["Guadalajara","Zapopan","San Pedro Tlaquepaque","Tonalá","Tlajomulco de Zúñiga","El Salto"],
    "Puebla": ["Puebla","San Andrés Cholula","Tlaxcalancingo","Amozoc","Apizaco","Tlaxcala","Chiautempan"],
    "Toluca": ["Toluca","Metepec","Zinacantepec","Lerma","Ocoyoacac","San Mateo Atenco"],
    "Tijuana": ["Tijuana","Tecate","Playas de Rosarito"],
    "León": ["León","Silao"],
    "Querétaro": ["Querétaro","Corregidora","El Marqués","Apaseo el Alto"],
    "Ciudad Juárez": ["Ciudad Juárez"],
    "La Laguna": ["Torreón","Gómez Palacio","Lerdo","Matamoros (Coah.)"],
    "Mérida": ["Mérida","Kanasín","Umán"],
    "San Luis Potosí": ["San Luis Potosí","Soledad de Graciano Sánchez"],
    "Aguascalientes": ["Aguascalientes","Jesús María","San Francisco de los Romo"],
    "Mexicali": ["Mexicali"],
    "Saltillo": ["Saltillo","Ramos Arizpe","Arteaga"],
    "Cuernavaca": ["Cuernavaca","Jiutepec","Temixco","Xochitepec","Emiliano Zapata"],
    "Culiacán": ["Culiacán"],
    "Morelia": ["Morelia","Tarímbaro","Charo"],
    "Chihuahua": ["Chihuahua"],
    "Veracruz": ["Veracruz","Boca del Río","Medellín","Alvarado"],
    "Hermosillo": ["Hermosillo"],
    "Cancún": ["Cancún","Isla Mujeres"],
    "Tampico": ["Tampico","Ciudad Madero","Altamira"],
    "Acapulco": ["Acapulco"],
    "Tuxtla Gutiérrez": ["Tuxtla Gutiérrez","Chiapa de Corzo","San Fernando"],
    "Reynosa": ["Reynosa","Río Bravo"],
    "Villahermosa": ["Villahermosa","Nacajuca"],
    "Xalapa": ["Xalapa","Coatepec","Emiliano Zapata (Ver.)","Banderilla"],
    "Celaya": ["Celaya","Cortázar","Comonfort","Villagrán"],
    "Oaxaca": ["Oaxaca","Xoxocotlán","San Bartolo Coyotepec","Tlalixtac de Cabrera"],
    "Durango": ["Durango"],
    "Pachuca": ["Pachuca","Mineral de la Reforma","Zempoala","Tizayuca"],
    "Tlaxcala–Apizaco": ["Tlaxcala","Apizaco","Chiautempan","Tetla de la Solidaridad"],
    "Matamoros": ["Matamoros"],
    "Poza Rica": ["Poza Rica","Coatzintla","Papantla"],
    "Mazatlán": ["Mazatlán"],
    "Tepic": ["Tepic","Xalisco"],
    "Cuautla": ["Cuautla","Yautepec","Ayala","Cuautla"],
    "Puerto Vallarta": ["Puerto Vallarta","Bahía de Banderas"],
    "Orizaba": ["Orizaba","Río Blanco","Nogales (Ver.)","Camerino Z. Mendoza"],
    "Ensenada": ["Ensenada"],
    "Nuevo Laredo": ["Nuevo Laredo"],
    "Zacatecas–Guadalupe": ["Zacatecas","Guadalupe","Trancoso"],
    "Colima–Villa de Álvarez": ["Colima","Villa de Álvarez","Comala","Coquimatlán"],
    "Monclova–Frontera": ["Monclova","Frontera","Castaños"],
    "Minatitlán": ["Minatitlán","Cosoleacaque","Ixhuatlán del Sureste"],
    "Tehuacán": ["Tehuacán","Ajalpan"],
    "Coatzacoalcos": ["Coatzacoalcos","Nanchital"],
    "Tapachula": ["Tapachula"],
    "Ciudad Victoria": ["Ciudad Victoria"],
    "Chilpancingo": ["Chilpancingo","Mochitlán"],
    "Córdoba": ["Córdoba","Fortín de las Flores","Amatlán de los Reyes"],
    "Campeche": ["Campeche"],
    "La Paz": ["La Paz"],
    "Zamora": ["Zamora","Jacona"],
    "Tulancingo": ["Tulancingo","Cuautepec de Hinojosa"],
    "Nogales": ["Nogales"],
    "Tula": ["Tula","Atotonilco de Tula","Tlahuelilpan"],
    "Chetumal": ["Chetumal"],
    "Piedras Negras": ["Piedras Negras","Nava"],
    "Guaymas": ["Guaymas","Empalme"],
    "Delicias": ["Delicias","Saucillo"],
    "Guanajuato": ["Guanajuato"],
    "Ocotlán": ["Ocotlán","Jamay","Poncitlán"],
    "Tehuantepec": ["Salina Cruz","Tehuantepec"],
    "Hidalgo del Parral": ["Hidalgo del Parral"],
    "Other": []
  },
  "United States": {
    "Alabama": ["Birmingham","Montgomery","Huntsville","Mobile","Tuscaloosa"],
    "Alaska": ["Anchorage","Fairbanks","Juneau"],
    "Arizona": ["Phoenix","Tucson","Mesa","Chandler","Scottsdale","Tempe","Gilbert","Glendale"],
    "Arkansas": ["Little Rock","Fayetteville","Fort Smith","Jonesboro"],
    "California": ["Los Ángeles","San Francisco","San Diego","San José","Sacramento","Oakland","Fresno","Long Beach","Bakersfield","Anaheim","Riverside","Stockton","Irvine"],
    "Colorado": ["Denver","Colorado Springs","Aurora","Fort Collins","Lakewood","Boulder"],
    "Connecticut": ["Bridgeport","New Haven","Hartford","Stamford"],
    "Florida": ["Miami","Orlando","Tampa","Jacksonville","Fort Lauderdale","St. Petersburg","Tallahassee","Port St. Lucie","Cape Coral","Pensacola"],
    "Georgia": ["Atlanta","Augusta","Columbus","Savannah","Athens"],
    "Hawaii": ["Honolulu","Pearl City","Hilo"],
    "Idaho": ["Boise","Nampa","Meridian"],
    "Illinois": ["Chicago","Aurora","Naperville","Rockford","Springfield","Joliet"],
    "Indiana": ["Indianapolis","Fort Wayne","Evansville","South Bend"],
    "Iowa": ["Des Moines","Cedar Rapids","Davenport"],
    "Kansas": ["Wichita","Overland Park","Kansas City","Topeka"],
    "Kentucky": ["Louisville","Lexington","Bowling Green"],
    "Louisiana": ["New Orleans","Baton Rouge","Shreveport","Lafayette"],
    "Maine": ["Portland","Lewiston","Bangor"],
    "Maryland": ["Baltimore","Frederick","Rockville","Gaithersburg"],
    "Massachusetts": ["Boston","Worcester","Springfield","Lowell","Cambridge"],
    "Michigan": ["Detroit","Grand Rapids","Warren","Lansing","Ann Arbor","Flint"],
    "Minnesota": ["Minneapolis","Saint Paul","Rochester","Duluth"],
    "Mississippi": ["Jackson","Gulfport","Hattiesburg"],
    "Missouri": ["Kansas City","St. Louis","Springfield","Columbia"],
    "Montana": ["Billings","Missoula","Great Falls"],
    "Nebraska": ["Omaha","Lincoln","Bellevue"],
    "Nevada": ["Las Vegas","Henderson","Reno","North Las Vegas"],
    "New Hampshire": ["Manchester","Nashua","Concord"],
    "New Jersey": ["Newark","Jersey City","Paterson","Elizabeth","Trenton"],
    "New Mexico": ["Albuquerque","Las Cruces","Santa Fe","Rio Rancho"],
    "New York": ["Nueva York","Buffalo","Rochester","Syracuse","Albany","Yonkers"],
    "North Carolina": ["Charlotte","Raleigh","Greensboro","Durham","Winston-Salem","Fayetteville"],
    "Ohio": ["Columbus","Cleveland","Cincinnati","Toledo","Akron","Dayton"],
    "Oklahoma": ["Oklahoma City","Tulsa","Norman","Broken Arrow"],
    "Oregon": ["Portland","Salem","Eugene","Gresham","Bend"],
    "Pennsylvania": ["Filadelfia","Pittsburgh","Allentown","Erie","Reading"],
    "Rhode Island": ["Providence","Cranston","Warwick"],
    "South Carolina": ["Columbia","Charleston","Greenville","Rock Hill"],
    "Tennessee": ["Nashville","Memphis","Knoxville","Chattanooga"],
    "Texas": ["Houston","Dallas","San Antonio","Austin","Fort Worth","El Paso","Arlington","Corpus Christi","Plano","Laredo","Lubbock","Garland","Frisco","McKinney"],
    "Utah": ["Salt Lake City","Provo","West Valley City","West Jordan"],
    "Vermont": ["Burlington","South Burlington"],
    "Virginia": ["Virginia Beach","Norfolk","Chesapeake","Richmond","Arlington","Alexandria"],
    "Washington": ["Seattle","Spokane","Tacoma","Vancouver","Bellevue","Everett"],
    "Washington DC": ["Washington DC"],
    "West Virginia": ["Charleston","Huntington","Morgantown"],
    "Wisconsin": ["Milwaukee","Madison","Green Bay","Kenosha"],
    "Wyoming": ["Cheyenne","Casper"],
    "Other": []
  },
  "España": {
    "Andalucía": ["Sevilla","Málaga","Granada","Córdoba","Almería","Jaén","Cádiz","Huelva","Marbella","Jerez de la Frontera"],
    "Aragón": ["Zaragoza","Huesca","Teruel"],
    "Asturias": ["Oviedo","Gijón","Avilés"],
    "Baleares": ["Palma","Ibiza","Mahón","Manacor"],
    "Canarias": ["Las Palmas","Santa Cruz de Tenerife","La Laguna","Telde"],
    "Cantabria": ["Santander","Torrelavega"],
    "Castilla-La Mancha": ["Toledo","Albacete","Ciudad Real","Cuenca","Guadalajara"],
    "Castilla y León": ["Valladolid","Burgos","Salamanca","León","Segovia","Ávila","Zamora","Palencia"],
    "Cataluña": ["Barcelona","Hospitalet de Llobregat","Badalona","Tarragona","Lleida","Sabadell","Terrassa","Girona"],
    "Comunidad Valenciana": ["Valencia","Alicante","Elche","Castellón","Torrevieja"],
    "Extremadura": ["Badajoz","Cáceres","Mérida","Plasencia"],
    "Galicia": ["Vigo","A Coruña","Ourense","Pontevedra","Santiago de Compostela","Lugo"],
    "La Rioja": ["Logroño","Calahorra"],
    "Madrid": ["Madrid","Móstoles","Alcalá de Henares","Fuenlabrada","Leganés","Getafe","Alcorcón","Torrejón de Ardoz"],
    "Murcia": ["Murcia","Cartagena","Lorca"],
    "Navarra": ["Pamplona","Tudela"],
    "País Vasco": ["Bilbao","San Sebastián","Vitoria","Barakaldo"],
    "Ceuta": ["Ceuta"],
    "Melilla": ["Melilla"],
    "Other": []
  },
  "Otro / Other": {}
};
